version: '2'
services:
  service-a:
    build: 
      context: ./service-a
      dockerfile: Dockerfile
    ports: 
      - 3001:3001
    environment:
      - PORT=3001

  service-b:
    build:
      context: ./service-b
      dockerfile: Dockerfile
    ports:
      - 3002:3002
    environment:
      - PORT=3002

  api-gateway:
    build: 
      context: ./api-gateway
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    environment:
      - SERVICE_A_URL=http://service-a:3001
      - SERVICE_B_URL=http://service-b:3002
      - PORT=3000
    depends_on:
      - service-a
      - service-b
